export default {
  MAX_PLAYERS: 6,
  MAX_HEARTBEAT_INTERVAL: 3000,
  CHECK_CONNECTION_INTERVAL: 500,
  SEND_STATE_INTERVAL: 250,
  TIME_TO_CHOOSE_ROLE: 30000,
  TIME_TO_VOTE_JOURNEY: 30000,
  TIME_TO_VOTE_SPY: 60000,
  TIME_INTERVAL: 1000,
  HOST_ID_LENGTH: 6,
  GAME_STATE: {
    PLAYERS_CONNECT: 0,
    CHOOSE_ROLE: 1,
    VOTE_JOURNEY: 2,
    ON_JOURNEY: 3,
    STATS_REVIEW: 4,
    VOTE_SPY: 5,
    JOURNEY_REVIEW: 6,
    GAME_REVIEW: 7,
  },
  COLORS: {
    BLACK: "#222222",
    WHITE: "#DDDDDD"
  }
};
